### ISSUE TITLE
flutter developer issue, Execution failed for task ':app:mergeDebugResources'.

### ISSUE THREAD

**Issue by rnooxx999** [pascalgrimaud/ansible-ubuntu#7]
i found a lot of salutation on android stdio 
but no results  on Intellij IDE 
i try to connect my device(Samsung) to  Intellij IDE  so i could  develop a flutter app
but there is problem show up, it says 
> Run with --stacktrace option Run with --info or --debug option 

and the real problem is : 
>FAILURE: Build failed with an exception.
What went wrong:
Execution failed for task ':app:mergeDebugResources'.
 java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource compilation failed

any help ?
i think my problem is in the setting & the compiler ?

**Comment by pascalgrimaud** [comment]
I don't understand at all what you're doing.
Is it related to ansible ?
Just give all steps to reproduce the issue you encounter with my repo, then, I'll be able to see if it's a bug or not.

**Comment by rnooxx999** [comment]
> I don't understand at all what you're doing.
> Is it related to ansible ?
> Just give all steps to reproduce the issue you encounter with my repo, then, I'll be able to see if it's a bug or not.

> Launching` lib\main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...
Resolving dependencies...
Running Gradle task 'assembleDebug'...
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:mergeDebugResources'.
> java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource compilation failed
  Output:  C:\new_project\testapp\android\app\src\main\res\drawable\launch_background.xml:12: error: not well-formed (invalid token).
  Command: C:\Users\Rno\.gradle\caches\transforms-1\files-1.1\aapt2-3.2.1-4818971-windows.jar\2217959b2fb1d14b23c83d7de1ff7bed\aapt2-3.2.1-4818971-windows\aapt2.exe compile --legacy \
          -o \
          C:\new_project\testapp\build\app\intermediates\res\merged\debug \
          C:\new_project\testapp\android\app\src\main\res\drawable\launch_background.xml
  Daemon:  AAPT2 aapt2-3.2.1-4818971-windows Daemon #2
 Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
 Get more help at https://help.gradle.org
BUILD FAILED in 20s
*******************************************************************************************
The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
See https://goo.gl/CP92wY for more information on the problem and how to fix it.
*******************************************************************************************
Finished with error: Gradle task assembleDebug failed with exit code 1

rno is my name 
testapp is my file name
thank you, i'd try to fix the problem for hours

**Comment by pascalgrimaud** [comment]
This repo is used for installing some tools in a Ubuntu machine. Nothing related to your specific Android project
So you're not opened the issue in the correct project

**Comment by rnooxx999** [comment]
> This repo is used for installing some tools in a Ubuntu machine. Nothing related to your specific Android project
> So you're not opened the issue in the correct project

i'm sorry, I'm a beginner in Android applications
should i delete my post ?

**Comment by pascalgrimaud** [comment]
no it's ok, the ticket is closed
Have a good day !
